### ISSUE TITLE
ESP32-WSPR build with ESP-IDF 5.3.1 fails

### ISSUE THREAD

**Issue by hrprada** [danak6jq/ESP32-WSPR#5]
error: unknown type name 'system_event_t'
  119 | static esp_err_t event_handler(void *ctx, system_event_t *event);

error: implicit declaration of function 'tcpip_adapter_init' [-Werror=implicit-function-declaration]
  172 |     tcpip_adapter_init();

error: implicit declaration of function 'esp_event_loop_init'; did you mean 'esp_event_loop_run'? [-Werror=implicit-function-declaration]
  174 |     ESP_ERROR_CHECK( esp_event_loop_init(event_handler, NULL) );

error: 'event_handler' undeclared (first use in this function); did you mean 'xt_handler'?
  174 |     ESP_ERROR_CHECK( esp_event_loop_init(event_handler, NULL) );

error: 'portTICK_RATE_MS' undeclared (first use in this function); did you mean 'portTICK_PERIOD_MS'?
  255 |     ret = i2c_master_cmd_begin(I2C_NUM_1, cmd, 1000 / portTICK_RATE_MS);
      |                                                       ^~~~~~~~~~~~~~~~

cc1.exe: some warnings being treated as errors
ninja: build stopped: subcommand failed.

**Comment by danak6jq** [comment]
Have you resolved this? Do you have a PR?
